#!/bin/bash
# save as ./decompress

BASENAME=`basename $0 .run`
echo ""
echo "Self Extracting Installer"
echo ""

#export TMPDIR=`mktemp -d /tmp/selfextract.XXXXXX`
export TMPDIR=${PWD}/tmp/extractpayload$RANDOM
mkdir -p $TMPDIR
chmod 700 $TMPDIR

ARCHIVE=`awk '/^__ARCHIVE_BELOW__/ {print NR + 1; exit 0; }' $0`

tail -n+$ARCHIVE $0 > ${TMPDIR}/${BASENAME}.tar.gz
tar xvfz ${TMPDIR}/${BASENAME}.tar.gz -C ${TMPDIR} &>/dev/null

CDIR=`pwd`
cd $TMPDIR
chmod 755 ./installer
./installer $1
cd $CDIR
rm -rf $TMPDIR

echo "Left overs removed."

exit 0

__ARCHIVE_BELOW__
